// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Channel struct {
	ChannelID              string `json:"channel_id"`
	ChannelName            string `json:"channel_name"`
	ChannelBackground      string `json:"channel_background"`
	ChannelIcon            string `json:"channel_icon"`
	ChannelSubscribers     int    `json:"channel_subscribers"`
	ChannelDescription     string `json:"channel_description"`
	ChannelJoinDateDay     int    `json:"channel_join_date_day"`
	ChannelJoinDateMonth   int    `json:"channel_join_date_month"`
	ChannelJoinDateYear    int    `json:"channel_join_date_year"`
	ChannelLikedVideo      string `json:"channel_liked_video"`
	ChannelDislikedVideo   string `json:"channel_disliked_video"`
	ChannelLikedPost       string `json:"channel_liked_post"`
	ChannelDislikedPost    string `json:"channel_disliked_post"`
	ChannelLikedComment    string `json:"channel_liked_comment"`
	ChannelDislikedComment string `json:"channel_disliked_comment"`
	ChannelPremium         string `json:"channel_premium"`
}

type Comment struct {
	CommentID  string `json:"comment_id"`
	ChannelID  string `json:"channel_id"`
	Like       int    `json:"like"`
	Dislike    int    `json:"dislike"`
	ReplyTo    int    `json:"reply_to"`
	Content    string `json:"content"`
	ReplyCount int    `json:"reply_count"`
	VideoID    int    `json:"video_id"`
	PostID     int    `json:"post_id"`
	Day        int    `json:"day"`
	Month      int    `json:"month"`
	Year       int    `json:"year"`
}

type Playlist struct {
	PlaylistID         string `json:"playlist_id"`
	ChannelID          string `json:"channel_id"`
	PlaylistTitle      string `json:"playlist_title"`
	PlaylistVisibility string `json:"playlist_visibility"`
	PlaylistDay        int    `json:"playlist_day"`
	PlaylistMonth      int    `json:"playlist_month"`
	PlaylistYear       int    `json:"playlist_year"`
	PlaylistViews      int    `json:"playlist_views"`
	PlaylistVideos     string `json:"playlist_videos"`
	PlaylistDesc       string `json:"playlist_desc"`
}

type Video struct {
	VideoID          string `json:"video_id"`
	VideoTitle       string `json:"video_title"`
	VideoDescription string `json:"video_description"`
	VideoCategory    string `json:"video_category"`
	VideoLike        int    `json:"video_like"`
	VideoDislike     int    `json:"video_dislike"`
	VideoPrivacy     string `json:"video_privacy"`
	VideoPremium     bool   `json:"video_premium"`
	VideoRestriction bool   `json:"video_restriction"`
	VideoThumbnail   string `json:"video_thumbnail"`
	Video            string `json:"video"`
	VideoViews       int    `json:"video_views"`
	VideoRegion      string `json:"video_region"`
	Day              int    `json:"day"`
	Month            int    `json:"month"`
	Year             int    `json:"year"`
	ChannelID        string `json:"channel_id"`
	ChannelName      string `json:"channel_name"`
	ChannelIcon      string `json:"channel_icon"`
}

type NewChannel struct {
	ChannelID              string `json:"channel_id"`
	ChannelName            string `json:"channel_name"`
	ChannelBackground      string `json:"channel_background"`
	ChannelIcon            string `json:"channel_icon"`
	ChannelSubscribers     int    `json:"channel_subscribers"`
	ChannelDescription     string `json:"channel_description"`
	ChannelJoinDateDay     int    `json:"channel_join_date_day"`
	ChannelJoinDateMonth   int    `json:"channel_join_date_month"`
	ChannelJoinDateYear    int    `json:"channel_join_date_year"`
	ChannelLikedVideo      string `json:"channel_liked_video"`
	ChannelDislikedVideo   string `json:"channel_disliked_video"`
	ChannelLikedPost       string `json:"channel_liked_post"`
	ChannelDislikedPost    string `json:"channel_disliked_post"`
	ChannelLikedComment    string `json:"channel_liked_comment"`
	ChannelDislikedComment string `json:"channel_disliked_comment"`
	ChannelPremium         string `json:"channel_premium"`
}

type NewComment struct {
	ChannelID  string `json:"channel_id"`
	Like       int    `json:"like"`
	Dislike    int    `json:"dislike"`
	ReplyTo    int    `json:"reply_to"`
	Content    string `json:"content"`
	ReplyCount int    `json:"reply_count"`
	VideoID    int    `json:"video_id"`
	PostID     int    `json:"post_id"`
	Day        int    `json:"day"`
	Month      int    `json:"month"`
	Year       int    `json:"year"`
}

type NewPlaylist struct {
	ChannelID          string `json:"channel_id"`
	PlaylistTitle      string `json:"playlist_title"`
	PlaylistVisibility string `json:"playlist_visibility"`
	PlaylistDay        int    `json:"playlist_day"`
	PlaylistMonth      int    `json:"playlist_month"`
	PlaylistYear       int    `json:"playlist_year"`
	PlaylistViews      int    `json:"playlist_views"`
	PlaylistVideos     string `json:"playlist_videos"`
	PlaylistDesc       string `json:"playlist_desc"`
}

type NewVideo struct {
	VideoTitle       string `json:"video_title"`
	VideoDescription string `json:"video_description"`
	VideoCategory    string `json:"video_category"`
	VideoLike        int    `json:"video_like"`
	VideoDislike     int    `json:"video_dislike"`
	VideoPrivacy     string `json:"video_privacy"`
	VideoPremium     bool   `json:"video_premium"`
	VideoRestriction bool   `json:"video_restriction"`
	VideoThumbnail   string `json:"video_thumbnail"`
	Video            string `json:"video"`
	VideoViews       int    `json:"video_views"`
	VideoRegion      string `json:"video_region"`
	Day              int    `json:"day"`
	Month            int    `json:"month"`
	Year             int    `json:"year"`
	ChannelID        string `json:"channel_id"`
	ChannelName      string `json:"channel_name"`
	ChannelIcon      string `json:"channel_icon"`
}
