// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Video struct {
	VideoID          string `json:"video_id"`
	VideoTitle       string `json:"video_title"`
	VideoDescription string `json:"video_description"`
	VideoCategory    string `json:"video_category"`
	VideoLike        int    `json:"video_like"`
	VideoDislike     int    `json:"video_dislike"`
	VideoPrivacy     string `json:"video_privacy"`
	VideoPremium     bool   `json:"video_premium"`
	VideoRestriction bool   `json:"video_restriction"`
	VideoThumbnail   string `json:"video_thumbnail"`
	Video            string `json:"video"`
	ChannelID        int    `json:"channel_id"`
	VideoViews       int    `json:"video_views"`
	VideoRegion      string `json:"video_region"`
	Day              int    `json:"day"`
	Month            int    `json:"month"`
	Year             int    `json:"year"`
}

type NewVideo struct {
	VideoTitle       string `json:"video_title"`
	VideoDescription string `json:"video_description"`
	VideoCategory    string `json:"video_category"`
	VideoLike        int    `json:"video_like"`
	VideoDislike     int    `json:"video_dislike"`
	VideoPrivacy     string `json:"video_privacy"`
	VideoPremium     bool   `json:"video_premium"`
	VideoRestriction bool   `json:"video_restriction"`
	VideoThumbnail   string `json:"video_thumbnail"`
	Video            string `json:"video"`
	ChannelID        int    `json:"channel_id"`
	VideoViews       int    `json:"video_views"`
	VideoRegion      string `json:"video_region"`
	Day              int    `json:"day"`
	Month            int    `json:"month"`
	Year             int    `json:"year"`
}
